version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: saiccess
      POSTGRES_PASSWORD: saiccess
      POSTGRES_DB: saiccess
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: {}